### ISSUE TITLE
Error in the build - 404 page

### ISSUE THREAD

**Issue by Zastinian** [NuroDev/astro-bun#1]
When you compile the code the 404 page does not work. 

![image](https://github.com/user-attachments/assets/a06f9a22-1cba-408d-8dd3-37035b33763a)

**Comment by NuroDev** [comment]
Hey @Zastinian, thank you for reporting this.

I have gone ahead and published version `1.1.4` which should fix this issue for you.

Let me know if you run into another issues 🙂
