### ISSUE TITLE
Can't set cookies with Bun

### ISSUE THREAD

**Issue by jadbox** [NuroDev/astro-bun#3]
> "@nurodev/astro-bun": "^1.1.4",
> "astro": "^4.13.1",

If I try to set any cookie in middleware or with an endpoint, it'll work using the development server. However, using the `astro build` production build, no cookie will get returned from the endpoint. If I switch from Bun to Node adapters, the cookies just work successfully in production. I also found I could use the Node adapter and still run the server with Bun without issue. The problem seems isolated to Bun's special Server package (see `import type { Server } from 'bun';` ).

I'm hoping someone may have better luck further troubleshooting than I.

**Comment by NuroDev** [comment]
Hey @jadbox, thanks for reporting this. I've just published a new version (`1.1.5`) that should fix this issue.

Looking into the official Node.js adapter it seems there was [a few additional options](https://github.com/withastro/astro/blob/main/packages/integrations/node/src/serve-app.ts#L39) that were missing when rendering each request

**Comment by jadbox** [comment]
@NuroDev thanks for fixing, seems to work now. It took me almost 3 days of debugging before I isolated the issue to not my code. Glad its fixed :)
