### ISSUE TITLE
Astro 5 deprecates hybrid mode, so 'static' mode will need to be supported

### ISSUE THREAD

**Issue by adworacz** [NuroDev/astro-bun#7]
Ref: https://astro.build/blog/astro-5-beta/#merged-static-and-hybrid-output-modes

Which means that this code now breaks compatibility with Astro 5: 

https://github.com/NuroDev/astro-bun/blob/main/package/src/index.ts#L54-L57

**Comment by Nicolab** [comment]
@NuroDev Thanks for this adapter. Do you plan to support Astro 5?

**Comment by NuroDev** [comment]
Hey everyone, thanks for flagging this.

I have gone ahead and published a new major package version (Version `2.0.0`) that fixes this package working with Astro version 5. I've tested the basics locally & all seems good and working like before, but if any other issues crop up, please feel free to open a new issue for it.

**Comment by Nicolab** [comment]
@NuroDev Oh great, it's Christmas before Christmas! 
Thank you ;)

**Comment by adworacz** [comment]
Excellent, thank you!
